// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRhQajZMpAIEddxZCXp_t1mfTO_Iqqps',
    appId: '1:88105829734:web:67ef7280776c32880434a7',
    messagingSenderId: '88105829734',
    projectId: 'ecoloop-mart',
    authDomain: 'ecoloop-mart.firebaseapp.com',
    storageBucket: 'ecoloop-mart.firebasestorage.app',
    measurementId: 'G-W0F400MW8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcawxS76p-o14dMczFTFdNvE2v1tYt0Ho',
    appId: '1:88105829734:android:bb29beb902bc37ea0434a7',
    messagingSenderId: '88105829734',
    projectId: 'ecoloop-mart',
    storageBucket: 'ecoloop-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARSayJ7r_4ZkKw-nsoFZzmLQ1CpXq2MpY',
    appId: '1:88105829734:ios:b10f9537c09bee0c0434a7',
    messagingSenderId: '88105829734',
    projectId: 'ecoloop-mart',
    storageBucket: 'ecoloop-mart.firebasestorage.app',
    iosBundleId: 'com.ecoloop.ecoloopMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARSayJ7r_4ZkKw-nsoFZzmLQ1CpXq2MpY',
    appId: '1:88105829734:ios:b10f9537c09bee0c0434a7',
    messagingSenderId: '88105829734',
    projectId: 'ecoloop-mart',
    storageBucket: 'ecoloop-mart.firebasestorage.app',
    iosBundleId: 'com.ecoloop.ecoloopMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlRhQajZMpAIEddxZCXp_t1mfTO_Iqqps',
    appId: '1:88105829734:web:0438fdc07ac12aa70434a7',
    messagingSenderId: '88105829734',
    projectId: 'ecoloop-mart',
    authDomain: 'ecoloop-mart.firebaseapp.com',
    storageBucket: 'ecoloop-mart.firebasestorage.app',
    measurementId: 'G-1FQ4RH3DJ0',
  );
}
